import { Inter } from "next/font/google";
import { CartContextProvider } from "./context/cartContext";
import Navbar from "./components/Navbar";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OBSTBOX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextProvider>
          <Navbar />
            {children}
        </CartContextProvider>
      </body>
    </html>
  );
}
